
export const getEvent = (id = null, soonEvents = false) => {
    const events = ref([
        { name: "Ain Sokhna", images: ["/trips/images/AinSokhna_1.jpg", "/trips/images/AinSokhna_2.jpg", "/trips/images/AinSokhna_3.jpg", "/trips/images/AinSokhna_4.jpg"], description: "Escape to a blissful ladies-only retreat in the picturesque Ain Sokhna, Egypt. Leave your worries behind and indulge yourself into a world of relaxation, rejuvenation, and fun. Enjoy the scenic coastal view and explore the nearby attractions. Go on a shopping spree in the local markets or enjoy a soothing spa treatment at the resort. Savor the authentic Egyptian cuisine and take part in the cultural activities and tours. Learn about the fascinating history of the region and enjoy the warm hospitality of the locals. Whether you seek an action-packed adventure or a serene getaway, Ain Sokhna offers it all. A ladies-only trip to Ain Sokhna is a perfect way to unwind and create unforgettable memories.", status: "Just announced!", date: "20/12/2023", price: '565.00' },
        { name: "Alexandria", images: ["/trips/images/Alexandria_1.jpg", "/trips/images/Alexandria_2.jpg"], description: "A ladies-only trip to Alexandria promises to be an unforgettable experience. As you explore this historic city, you'll be surrounded by towering ancient architecture, bustling markets, and mouth-watering food. Begin your adventure at the iconic Bibliotheca Alexandrina, soaking in the knowledge and culture of this ancient city. Take a stroll through the charming streets of the European quarter, savoring delectable Egyptian street food, and admiring the city's stunning coastline. For a luxurious and relaxing experience, visit the Four Seasons Hotel Alexandria and indulge in spa treatments. Explore the ancient catacombs and forts, and sip on traditional Egyptian teas while appreciating the ingenuity of this vibrant culture. This trip is sure to leave you feeling rejuvenated, enlightened, and more connected to the richness of ancient Alexandria.", status: "Just announced!", date: "10/2/2024", price: '450.00' },
        { name: "Dahab", images: ["/trips/images/Dahab_1.jpg", "/trips/images/Dahab_2.jpg", "/trips/images/Dahab_3.jpg"], description: "Imagine the peaceful ambience of Dahab, with its serene turquoise beaches lined with swaying palm trees and a stunning view of the Sinai Mountains. Now, picture enjoying this paradise with your closest girlfriends, as you bond over yoga sessions, indulge in spa treatments, and immerse yourself in the local culture. A ladies-only trip to Dahab promises a rejuvenating getaway, away from the hustle and bustle of everyday life. With its laid-back vibe, pristine beaches, and exceptional seafood, you'll get to escape the stresses of work and embrace the simpler things in life. From snorkeling expeditions to camel riding, Dahab promises an unforgettable experience for every woman seeking a little slice of paradise.", status: "Just announced!", date: "15/8/2024", price: '1145.00' },
        { name: "Yakht Trip", images: ["/trips/images/YakhtTrip_1.jpg", "/trips/images/YakhtTrip_2.jpg", "/trips/images/YakhtTrip_3.jpg"], description: "خروجة الماميز الجاية اللى كلكم سألتونا عليها  هتكون التلات الجاى ان شاء الله ٣١ /١٠  من الساعة ١٠ص نكون فى اليخت و بنخلص ١:٣٠ اليخت برايفت لينا ثابت ساعة و نص و متحرك ساعتين شاملة فطار اوبن بوفيه (فول ،  طعمية ،  بيض ، جبنة بطماطم ، مخلل ، سلطات ، عيش ، فطير فلاحى ، عسل ، شاى) و شو فنون شعبية", status: "Just announced!", date: "8/11/2023", price: '750.00' },
        { name: 'Cornish El Nile', images: ['/trips/images/El_nile_1.jpg', '/trips/images/El_nile_2.jpg', '/trips/images/El_nile_3.jpg', '/trips/images/El_nile_4.jpg', '/trips/images/El_nile_5.jpg'], description: "Stay Tuned!", status: "Comming soon!", date: "25/12/2023", price: '325.00' },
        { name: "Alexandria", images: ["/trips/images/Alexandria_1.jpg", "/trips/images/Alexandria_2.jpg"], description: "Stay tuned!", status: "Comming soon!", date: "5/9/2024", price: '450.00' },
        { name: "Ain Sokhna", images: ["/trips/images/AinSokhna_1.jpg", "/trips/images/AinSokhna_2.jpg", "/trips/images/AinSokhna_3.jpg", "/trips/images/AinSokhna_4.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident tempora incidunt totam deleniti est voluptates illum iste sequi nobis quibusdam necessitatibus pariatur, exercitationem natus repudiandae dignissimos dolorum eveniet a placeat.", status: "Comming soon!", date: "1/12/2023", price: "535.00" },
        { name: "Luxor X Aswan", images: ["/trips/images/Luxor_1.jpg", "/trips/images/Luxor_2.jpg", "/trips/images/Luxor_3.jpg", "/trips/images/Luxor_4.jpg", "/trips/images/Luxor_5.jpg", "/trips/images/Luxor_6.jpg", "/trips/images/Luxor_7.jpeg"], description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident tempora incidunt totam deleniti est voluptates illum iste sequi nobis quibusdam necessitatibus pariatur, exercitationem natus repudiandae dignissimos dolorum eveniet a placeat.", status: "Comming soon!", date: "1/1/2024", price: "5450.00" },
        { name: "Dahab", images: ["/trips/images/Dahab_1.jpg", "/trips/images/Dahab_2.jpg", "/trips/images/Dahab_3.jpg"], description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident tempora incidunt totam deleniti est voluptates illum iste sequi nobis quibusdam necessitatibus pariatur, exercitationem natus repudiandae dignissimos dolorum eveniet a placeat.", status: "10 days remaining!", date: "21/11/2023", price: "3200.00" },
    ])
    if (soonEvents && !id)
        return events.value.filter((row) => {
            if (row.status == 'Comming soon!')
                return row;
        })
    else
        return id ? events.value[id] : events.value;
}